language: python
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run ./manage.py test --settings=django_kids.settings.test
after_success:
  - coveralls
