language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - cd src
  - coverage run ./manage.py test --settings=django_kids.settings.test
  - cd ..
  - mv src/.coverage ./.coverage
  - mv src/.coveragerc ./.coveragerc
after_success:
  - coveralls
